# Generated by Django 2.2.1 on 2020-06-01 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='english',
            new_name='from_lang',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='other',
            new_name='other_word',
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='from_word',
            field=models.CharField(default='blep', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='translation',
            name='other_lang',
            field=models.CharField(max_length=100),
        ),
    ]
